### ISSUE TITLE
Deploy the basic webpage

### ISSUE THREAD

**Issue by puneethkanna** [narlaapoorva/learning#2]
Deploy the static webpage in github pages.

**Comment by narlaapoorva** [comment]
deployed.

**Comment by puneethkanna** [comment]
Please provide the link.

**Comment by puneethkanna** [comment]
Close the issue after the link works..

**Comment by narlaapoorva** [comment]
https://narlaapoorva.github.io/learning/
check if the link works.

**Comment by puneethkanna** [comment]
It is working!
Now we can close the issue.
